name: metrics
channels:
- peterjc123
- menpo
- conda-forge
- defaults
- anaconda
- powerai
dependencies:
- python=3.6
- pytorch
- torchvision==0.2.1
- scipy
- scikit-image
- scikit-learn
- tensorflow-gpu==1.12
- gin-config
- opencv3
- ipython
- pip:
  - Pillow==6.0.0
  - numpy
  - matplotlib
  - tqdm